# Generated by Django 3.2.9 on 2021-12-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField(default=0)),
                ('pi', models.FloatField(default=3.14)),
                ('h', models.FloatField(default=0)),
                ('s', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField(default=0)),
                ('pi', models.FloatField(default=3.14)),
                ('h', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RectangularPrism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.FloatField(default=0)),
                ('w', models.FloatField(default=0)),
                ('l', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField(default=0)),
                ('pi', models.FloatField(default=3.14)),
            ],
        ),
        migrations.CreateModel(
            name='TriangularPrism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.FloatField(default=0)),
                ('h', models.FloatField(default=0)),
                ('l', models.FloatField(default=0)),
                ('s', models.FloatField(default=0)),
            ],
        ),
    ]
