# Generated by Django 3.2.9 on 2021-12-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sphere',
            name='area',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cone',
            name='h',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='cone',
            name='pi',
            field=models.FloatField(default=3.14, max_length=20),
        ),
        migrations.AlterField(
            model_name='cone',
            name='radius',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='cone',
            name='s',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='h',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='pi',
            field=models.FloatField(default=3.14, max_length=20),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='radius',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='rectangularprism',
            name='h',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='rectangularprism',
            name='l',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='rectangularprism',
            name='w',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='sphere',
            name='pi',
            field=models.DecimalField(decimal_places=10, default=3.14, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sphere',
            name='radius',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='triangularprism',
            name='b',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='triangularprism',
            name='h',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='triangularprism',
            name='l',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='triangularprism',
            name='s',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
