# Generated by Django 3.2.9 on 2021-12-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculating', '0002_auto_20211221_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cone',
            old_name='radius',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='cylinder',
            old_name='radius',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='sphere',
            old_name='radius',
            new_name='r',
        ),
    ]
