# Generated by Django 3.2.9 on 2021-12-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculating', '0003_auto_20211223_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cone',
        ),
        migrations.DeleteModel(
            name='Cylinder',
        ),
        migrations.DeleteModel(
            name='RectangularPrism',
        ),
        migrations.DeleteModel(
            name='Sphere',
        ),
        migrations.DeleteModel(
            name='TriangularPrism',
        ),
    ]
